namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.btnDong = new System.Windows.Forms.Button();
            this.tabDanhMuc = new System.Windows.Forms.TabControl();
            this.tp1 = new System.Windows.Forms.TabPage();
            this.tp2 = new System.Windows.Forms.TabPage();
            this.tp3 = new System.Windows.Forms.TabPage();
            this.tp4 = new System.Windows.Forms.TabPage();
            this.dgvPT = new System.Windows.Forms.DataGridView();
            this.lblCap_txtPTMa = new System.Windows.Forms.Label();
            this.txtPTMa = new System.Windows.Forms.TextBox();
            this.lblCap_txtPTTen = new System.Windows.Forms.Label();
            this.txtPTTen = new System.Windows.Forms.TextBox();
            this.lblCap_txtPTGhiChu = new System.Windows.Forms.Label();
            this.txtPTGhiChu = new System.Windows.Forms.TextBox();
            this.btnThemPT = new System.Windows.Forms.Button();
            this.dgvDB = new System.Windows.Forms.DataGridView();
            this.lblCap_txtDBMa = new System.Windows.Forms.Label();
            this.txtDBMa = new System.Windows.Forms.TextBox();
            this.lblCap_txtDBTen = new System.Windows.Forms.Label();
            this.txtDBTen = new System.Windows.Forms.TextBox();
            this.lblCap_txtDBDiaChi = new System.Windows.Forms.Label();
            this.txtDBDiaChi = new System.Windows.Forms.TextBox();
            this.lblCap_txtDBDT = new System.Windows.Forms.Label();
            this.txtDBDT = new System.Windows.Forms.TextBox();
            this.btnThemDB = new System.Windows.Forms.Button();
            this.dgvHDV = new System.Windows.Forms.DataGridView();
            this.lblCap_txtHDVMa = new System.Windows.Forms.Label();
            this.txtHDVMa = new System.Windows.Forms.TextBox();
            this.lblCap_txtHDVTen = new System.Windows.Forms.Label();
            this.txtHDVTen = new System.Windows.Forms.TextBox();
            this.lblCap_txtHDVDT = new System.Windows.Forms.Label();
            this.txtHDVDT = new System.Windows.Forms.TextBox();
            this.lblCap_numLuong = new System.Windows.Forms.Label();
            this.numLuong = new System.Windows.Forms.NumericUpDown();
            this.btnThemHDV = new System.Windows.Forms.Button();
            this.dgvDTQ = new System.Windows.Forms.DataGridView();
            this.lblCap_txtDTQMa = new System.Windows.Forms.Label();
            this.txtDTQMa = new System.Windows.Forms.TextBox();
            this.lblCap_txtDTQTen = new System.Windows.Forms.Label();
            this.txtDTQTen = new System.Windows.Forms.TextBox();
            this.lblCap_txtDTQDiaDiem = new System.Windows.Forms.Label();
            this.txtDTQDiaDiem = new System.Windows.Forms.TextBox();
            this.lblCap_txtDTQNoiDung = new System.Windows.Forms.Label();
            this.txtDTQNoiDung = new System.Windows.Forms.TextBox();
            this.lblCap_txtDTQYNghia = new System.Windows.Forms.Label();
            this.txtDTQYNghia = new System.Windows.Forms.TextBox();
            this.btnThemDTQ = new System.Windows.Forms.Button();
            this.pnlHeader.SuspendLayout();
            this.tabDanhMuc.SuspendLayout();
            this.tp1.SuspendLayout();
            this.tp2.SuspendLayout();
            this.tp3.SuspendLayout();
            this.tp4.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.SystemColors.Window;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Size = new System.Drawing.Size(900, 56);
            this.pnlHeader.TabIndex = 0;
            this.pnlHeader.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblTitle.Text = "DANH MỤC";
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Regular);
            this.lblTitle.Location = new System.Drawing.Point(16, 13);
            this.lblTitle.TabIndex = 1;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Location = new System.Drawing.Point(784, 12);
            this.btnDong.Size = new System.Drawing.Size(100, 32);
            this.btnDong.TabIndex = 2;
            this.btnDong.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.dgvPT.AllowUserToAddRows = false;
            this.dgvPT.AllowUserToDeleteRows = false;
            this.dgvPT.ReadOnly = true;
            this.dgvPT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPT.MultiSelect = false;
            this.dgvPT.RowHeadersVisible = false;
            this.dgvPT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPT.BackgroundColor = System.Drawing.Color.White;
            this.dgvPT.Location = new System.Drawing.Point(10, 8);
            this.dgvPT.Size = new System.Drawing.Size(840, 170);
            this.dgvPT.TabIndex = 3;
            this.dgvPT.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_txtPTMa.Text = "Mã PT:";
            this.lblCap_txtPTMa.AutoSize = true;
            this.lblCap_txtPTMa.Location = new System.Drawing.Point(14, 195);
            this.lblCap_txtPTMa.TabIndex = 4;
            this.txtPTMa.Location = new System.Drawing.Point(164, 190);
            this.txtPTMa.Size = new System.Drawing.Size(242, 23);
            this.txtPTMa.TabIndex = 5;
            this.lblCap_txtPTTen.Text = "Tên PT:";
            this.lblCap_txtPTTen.AutoSize = true;
            this.lblCap_txtPTTen.Location = new System.Drawing.Point(430, 195);
            this.lblCap_txtPTTen.TabIndex = 6;
            this.txtPTTen.Location = new System.Drawing.Point(580, 190);
            this.txtPTTen.Size = new System.Drawing.Size(242, 23);
            this.txtPTTen.TabIndex = 7;
            this.lblCap_txtPTGhiChu.Text = "Ghi chú:";
            this.lblCap_txtPTGhiChu.AutoSize = true;
            this.lblCap_txtPTGhiChu.Location = new System.Drawing.Point(14, 229);
            this.lblCap_txtPTGhiChu.TabIndex = 8;
            this.txtPTGhiChu.Location = new System.Drawing.Point(164, 224);
            this.txtPTGhiChu.Size = new System.Drawing.Size(682, 23);
            this.txtPTGhiChu.TabIndex = 9;
            this.btnThemPT.Text = "Thêm";
            this.btnThemPT.UseVisualStyleBackColor = true;
            this.btnThemPT.Location = new System.Drawing.Point(10, 264);
            this.btnThemPT.Size = new System.Drawing.Size(120, 36);
            this.btnThemPT.TabIndex = 10;
            this.dgvDB.AllowUserToAddRows = false;
            this.dgvDB.AllowUserToDeleteRows = false;
            this.dgvDB.ReadOnly = true;
            this.dgvDB.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDB.MultiSelect = false;
            this.dgvDB.RowHeadersVisible = false;
            this.dgvDB.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDB.BackgroundColor = System.Drawing.Color.White;
            this.dgvDB.Location = new System.Drawing.Point(10, 8);
            this.dgvDB.Size = new System.Drawing.Size(840, 170);
            this.dgvDB.TabIndex = 11;
            this.dgvDB.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_txtDBMa.Text = "Mã điểm bán:";
            this.lblCap_txtDBMa.AutoSize = true;
            this.lblCap_txtDBMa.Location = new System.Drawing.Point(14, 195);
            this.lblCap_txtDBMa.TabIndex = 12;
            this.txtDBMa.Location = new System.Drawing.Point(164, 190);
            this.txtDBMa.Size = new System.Drawing.Size(242, 23);
            this.txtDBMa.TabIndex = 13;
            this.lblCap_txtDBTen.Text = "Tên điểm bán:";
            this.lblCap_txtDBTen.AutoSize = true;
            this.lblCap_txtDBTen.Location = new System.Drawing.Point(430, 195);
            this.lblCap_txtDBTen.TabIndex = 14;
            this.txtDBTen.Location = new System.Drawing.Point(580, 190);
            this.txtDBTen.Size = new System.Drawing.Size(242, 23);
            this.txtDBTen.TabIndex = 15;
            this.lblCap_txtDBDiaChi.Text = "Địa chỉ:";
            this.lblCap_txtDBDiaChi.AutoSize = true;
            this.lblCap_txtDBDiaChi.Location = new System.Drawing.Point(14, 229);
            this.lblCap_txtDBDiaChi.TabIndex = 16;
            this.txtDBDiaChi.Location = new System.Drawing.Point(164, 224);
            this.txtDBDiaChi.Size = new System.Drawing.Size(682, 23);
            this.txtDBDiaChi.TabIndex = 17;
            this.lblCap_txtDBDT.Text = "Điện thoại:";
            this.lblCap_txtDBDT.AutoSize = true;
            this.lblCap_txtDBDT.Location = new System.Drawing.Point(14, 263);
            this.lblCap_txtDBDT.TabIndex = 18;
            this.txtDBDT.Location = new System.Drawing.Point(164, 258);
            this.txtDBDT.Size = new System.Drawing.Size(242, 23);
            this.txtDBDT.TabIndex = 19;
            this.btnThemDB.Text = "Thêm";
            this.btnThemDB.UseVisualStyleBackColor = true;
            this.btnThemDB.Location = new System.Drawing.Point(10, 298);
            this.btnThemDB.Size = new System.Drawing.Size(120, 36);
            this.btnThemDB.TabIndex = 20;
            this.dgvHDV.AllowUserToAddRows = false;
            this.dgvHDV.AllowUserToDeleteRows = false;
            this.dgvHDV.ReadOnly = true;
            this.dgvHDV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvHDV.MultiSelect = false;
            this.dgvHDV.RowHeadersVisible = false;
            this.dgvHDV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvHDV.BackgroundColor = System.Drawing.Color.White;
            this.dgvHDV.Location = new System.Drawing.Point(10, 8);
            this.dgvHDV.Size = new System.Drawing.Size(840, 170);
            this.dgvHDV.TabIndex = 21;
            this.dgvHDV.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_txtHDVMa.Text = "Mã HDV:";
            this.lblCap_txtHDVMa.AutoSize = true;
            this.lblCap_txtHDVMa.Location = new System.Drawing.Point(14, 195);
            this.lblCap_txtHDVMa.TabIndex = 22;
            this.txtHDVMa.Location = new System.Drawing.Point(164, 190);
            this.txtHDVMa.Size = new System.Drawing.Size(242, 23);
            this.txtHDVMa.TabIndex = 23;
            this.lblCap_txtHDVTen.Text = "Họ tên:";
            this.lblCap_txtHDVTen.AutoSize = true;
            this.lblCap_txtHDVTen.Location = new System.Drawing.Point(430, 195);
            this.lblCap_txtHDVTen.TabIndex = 24;
            this.txtHDVTen.Location = new System.Drawing.Point(580, 190);
            this.txtHDVTen.Size = new System.Drawing.Size(242, 23);
            this.txtHDVTen.TabIndex = 25;
            this.lblCap_txtHDVDT.Text = "Điện thoại:";
            this.lblCap_txtHDVDT.AutoSize = true;
            this.lblCap_txtHDVDT.Location = new System.Drawing.Point(14, 229);
            this.lblCap_txtHDVDT.TabIndex = 26;
            this.txtHDVDT.Location = new System.Drawing.Point(164, 224);
            this.txtHDVDT.Size = new System.Drawing.Size(242, 23);
            this.txtHDVDT.TabIndex = 27;
            this.lblCap_numLuong.Text = "Lương căn bản:";
            this.lblCap_numLuong.AutoSize = true;
            this.lblCap_numLuong.Location = new System.Drawing.Point(430, 229);
            this.lblCap_numLuong.TabIndex = 28;
            this.numLuong.Minimum = new decimal(new int[] {0, 0, 0, 0});
            this.numLuong.Maximum = new decimal(new int[] {2000000000, 0, 0, 0});
            this.numLuong.Increment = new decimal(new int[] {100000, 0, 0, 0});
            this.numLuong.ThousandsSeparator = true;
            this.numLuong.Value = new decimal(new int[] {0, 0, 0, 0});
            this.numLuong.Location = new System.Drawing.Point(580, 224);
            this.numLuong.Size = new System.Drawing.Size(180, 23);
            this.numLuong.TabIndex = 29;
            this.btnThemHDV.Text = "Thêm";
            this.btnThemHDV.UseVisualStyleBackColor = true;
            this.btnThemHDV.Location = new System.Drawing.Point(10, 264);
            this.btnThemHDV.Size = new System.Drawing.Size(120, 36);
            this.btnThemHDV.TabIndex = 30;
            this.dgvDTQ.AllowUserToAddRows = false;
            this.dgvDTQ.AllowUserToDeleteRows = false;
            this.dgvDTQ.ReadOnly = true;
            this.dgvDTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDTQ.MultiSelect = false;
            this.dgvDTQ.RowHeadersVisible = false;
            this.dgvDTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDTQ.BackgroundColor = System.Drawing.Color.White;
            this.dgvDTQ.Location = new System.Drawing.Point(10, 8);
            this.dgvDTQ.Size = new System.Drawing.Size(840, 170);
            this.dgvDTQ.TabIndex = 31;
            this.dgvDTQ.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_txtDTQMa.Text = "Mã điểm TQ:";
            this.lblCap_txtDTQMa.AutoSize = true;
            this.lblCap_txtDTQMa.Location = new System.Drawing.Point(14, 195);
            this.lblCap_txtDTQMa.TabIndex = 32;
            this.txtDTQMa.Location = new System.Drawing.Point(164, 190);
            this.txtDTQMa.Size = new System.Drawing.Size(242, 23);
            this.txtDTQMa.TabIndex = 33;
            this.lblCap_txtDTQTen.Text = "Tên điểm TQ:";
            this.lblCap_txtDTQTen.AutoSize = true;
            this.lblCap_txtDTQTen.Location = new System.Drawing.Point(430, 195);
            this.lblCap_txtDTQTen.TabIndex = 34;
            this.txtDTQTen.Location = new System.Drawing.Point(580, 190);
            this.txtDTQTen.Size = new System.Drawing.Size(242, 23);
            this.txtDTQTen.TabIndex = 35;
            this.lblCap_txtDTQDiaDiem.Text = "Địa điểm:";
            this.lblCap_txtDTQDiaDiem.AutoSize = true;
            this.lblCap_txtDTQDiaDiem.Location = new System.Drawing.Point(14, 229);
            this.lblCap_txtDTQDiaDiem.TabIndex = 36;
            this.txtDTQDiaDiem.Location = new System.Drawing.Point(164, 224);
            this.txtDTQDiaDiem.Size = new System.Drawing.Size(242, 23);
            this.txtDTQDiaDiem.TabIndex = 37;
            this.lblCap_txtDTQNoiDung.Text = "Nội dung:";
            this.lblCap_txtDTQNoiDung.AutoSize = true;
            this.lblCap_txtDTQNoiDung.Location = new System.Drawing.Point(14, 263);
            this.lblCap_txtDTQNoiDung.TabIndex = 38;
            this.txtDTQNoiDung.Location = new System.Drawing.Point(164, 258);
            this.txtDTQNoiDung.Size = new System.Drawing.Size(682, 23);
            this.txtDTQNoiDung.TabIndex = 39;
            this.lblCap_txtDTQYNghia.Text = "Ý nghĩa:";
            this.lblCap_txtDTQYNghia.AutoSize = true;
            this.lblCap_txtDTQYNghia.Location = new System.Drawing.Point(14, 297);
            this.lblCap_txtDTQYNghia.TabIndex = 40;
            this.txtDTQYNghia.Location = new System.Drawing.Point(164, 292);
            this.txtDTQYNghia.Size = new System.Drawing.Size(682, 23);
            this.txtDTQYNghia.TabIndex = 41;
            this.btnThemDTQ.Text = "Thêm";
            this.btnThemDTQ.UseVisualStyleBackColor = true;
            this.btnThemDTQ.Location = new System.Drawing.Point(10, 332);
            this.btnThemDTQ.Size = new System.Drawing.Size(120, 36);
            this.btnThemDTQ.TabIndex = 42;
            this.tp1.Text = "Phương tiện";
            this.tp1.UseVisualStyleBackColor = true;
            this.tp1.Location = new System.Drawing.Point(4, 26);
            this.tp1.Size = new System.Drawing.Size(860, 386);
            this.tp1.TabIndex = 43;
            this.tp2.Text = "Điểm bán vé";
            this.tp2.UseVisualStyleBackColor = true;
            this.tp2.Location = new System.Drawing.Point(4, 26);
            this.tp2.Size = new System.Drawing.Size(860, 386);
            this.tp2.TabIndex = 44;
            this.tp3.Text = "Hướng dẫn viên";
            this.tp3.UseVisualStyleBackColor = true;
            this.tp3.Location = new System.Drawing.Point(4, 26);
            this.tp3.Size = new System.Drawing.Size(860, 386);
            this.tp3.TabIndex = 45;
            this.tp4.Text = "Điểm tham quan";
            this.tp4.UseVisualStyleBackColor = true;
            this.tp4.Location = new System.Drawing.Point(4, 26);
            this.tp4.Size = new System.Drawing.Size(860, 386);
            this.tp4.TabIndex = 46;
            this.tabDanhMuc.Location = new System.Drawing.Point(16, 70);
            this.tabDanhMuc.Size = new System.Drawing.Size(868, 418);
            this.tabDanhMuc.TabIndex = 47;
            this.tabDanhMuc.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.pnlHeader.Controls.Add(this.lblTitle);
            this.pnlHeader.Controls.Add(this.btnDong);
            this.Controls.Add(this.pnlHeader);
            this.tp1.Controls.Add(this.dgvPT);
            this.tp1.Controls.Add(this.lblCap_txtPTMa);
            this.tp1.Controls.Add(this.txtPTMa);
            this.tp1.Controls.Add(this.lblCap_txtPTTen);
            this.tp1.Controls.Add(this.txtPTTen);
            this.tp1.Controls.Add(this.lblCap_txtPTGhiChu);
            this.tp1.Controls.Add(this.txtPTGhiChu);
            this.tp1.Controls.Add(this.btnThemPT);
            this.tp2.Controls.Add(this.dgvDB);
            this.tp2.Controls.Add(this.lblCap_txtDBMa);
            this.tp2.Controls.Add(this.txtDBMa);
            this.tp2.Controls.Add(this.lblCap_txtDBTen);
            this.tp2.Controls.Add(this.txtDBTen);
            this.tp2.Controls.Add(this.lblCap_txtDBDiaChi);
            this.tp2.Controls.Add(this.txtDBDiaChi);
            this.tp2.Controls.Add(this.lblCap_txtDBDT);
            this.tp2.Controls.Add(this.txtDBDT);
            this.tp2.Controls.Add(this.btnThemDB);
            this.tp3.Controls.Add(this.dgvHDV);
            this.tp3.Controls.Add(this.lblCap_txtHDVMa);
            this.tp3.Controls.Add(this.txtHDVMa);
            this.tp3.Controls.Add(this.lblCap_txtHDVTen);
            this.tp3.Controls.Add(this.txtHDVTen);
            this.tp3.Controls.Add(this.lblCap_txtHDVDT);
            this.tp3.Controls.Add(this.txtHDVDT);
            this.tp3.Controls.Add(this.lblCap_numLuong);
            this.tp3.Controls.Add(this.numLuong);
            this.tp3.Controls.Add(this.btnThemHDV);
            this.tp4.Controls.Add(this.dgvDTQ);
            this.tp4.Controls.Add(this.lblCap_txtDTQMa);
            this.tp4.Controls.Add(this.txtDTQMa);
            this.tp4.Controls.Add(this.lblCap_txtDTQTen);
            this.tp4.Controls.Add(this.txtDTQTen);
            this.tp4.Controls.Add(this.lblCap_txtDTQDiaDiem);
            this.tp4.Controls.Add(this.txtDTQDiaDiem);
            this.tp4.Controls.Add(this.lblCap_txtDTQNoiDung);
            this.tp4.Controls.Add(this.txtDTQNoiDung);
            this.tp4.Controls.Add(this.lblCap_txtDTQYNghia);
            this.tp4.Controls.Add(this.txtDTQYNghia);
            this.tp4.Controls.Add(this.btnThemDTQ);
            this.tabDanhMuc.Controls.Add(this.tp1);
            this.tabDanhMuc.Controls.Add(this.tp2);
            this.tabDanhMuc.Controls.Add(this.tp3);
            this.tabDanhMuc.Controls.Add(this.tp4);
            this.Controls.Add(this.tabDanhMuc);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(900, 504);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "FrmDanhMuc";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Danh mục";
            this.AutoScroll = true;
            this.btnThemPT.Click += new System.EventHandler(this.btnThemPT_Click);
            this.btnThemDB.Click += new System.EventHandler(this.btnThemDB_Click);
            this.btnThemHDV.Click += new System.EventHandler(this.btnThemHDV_Click);
            this.btnThemDTQ.Click += new System.EventHandler(this.btnThemDTQ_Click);
            this.btnThemPT.Click += new System.EventHandler(this.btnThemPT_Click);
            this.btnThemDB.Click += new System.EventHandler(this.btnThemDB_Click);
            this.btnThemHDV.Click += new System.EventHandler(this.btnThemHDV_Click);
            this.btnThemDTQ.Click += new System.EventHandler(this.btnThemDTQ_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Load += new System.EventHandler(this.FrmDanhMuc_Load);
            this.pnlHeader.ResumeLayout(false);
            this.tabDanhMuc.ResumeLayout(false);
            this.tp1.ResumeLayout(false);
            this.tp2.ResumeLayout(false);
            this.tp3.ResumeLayout(false);
            this.tp4.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.TabControl tabDanhMuc;
        private System.Windows.Forms.TabPage tp1;
        private System.Windows.Forms.TabPage tp2;
        private System.Windows.Forms.TabPage tp3;
        private System.Windows.Forms.TabPage tp4;
        private System.Windows.Forms.DataGridView dgvPT;
        private System.Windows.Forms.Label lblCap_txtPTMa;
        private System.Windows.Forms.TextBox txtPTMa;
        private System.Windows.Forms.Label lblCap_txtPTTen;
        private System.Windows.Forms.TextBox txtPTTen;
        private System.Windows.Forms.Label lblCap_txtPTGhiChu;
        private System.Windows.Forms.TextBox txtPTGhiChu;
        private System.Windows.Forms.Button btnThemPT;
        private System.Windows.Forms.DataGridView dgvDB;
        private System.Windows.Forms.Label lblCap_txtDBMa;
        private System.Windows.Forms.TextBox txtDBMa;
        private System.Windows.Forms.Label lblCap_txtDBTen;
        private System.Windows.Forms.TextBox txtDBTen;
        private System.Windows.Forms.Label lblCap_txtDBDiaChi;
        private System.Windows.Forms.TextBox txtDBDiaChi;
        private System.Windows.Forms.Label lblCap_txtDBDT;
        private System.Windows.Forms.TextBox txtDBDT;
        private System.Windows.Forms.Button btnThemDB;
        private System.Windows.Forms.DataGridView dgvHDV;
        private System.Windows.Forms.Label lblCap_txtHDVMa;
        private System.Windows.Forms.TextBox txtHDVMa;
        private System.Windows.Forms.Label lblCap_txtHDVTen;
        private System.Windows.Forms.TextBox txtHDVTen;
        private System.Windows.Forms.Label lblCap_txtHDVDT;
        private System.Windows.Forms.TextBox txtHDVDT;
        private System.Windows.Forms.Label lblCap_numLuong;
        private System.Windows.Forms.NumericUpDown numLuong;
        private System.Windows.Forms.Button btnThemHDV;
        private System.Windows.Forms.DataGridView dgvDTQ;
        private System.Windows.Forms.Label lblCap_txtDTQMa;
        private System.Windows.Forms.TextBox txtDTQMa;
        private System.Windows.Forms.Label lblCap_txtDTQTen;
        private System.Windows.Forms.TextBox txtDTQTen;
        private System.Windows.Forms.Label lblCap_txtDTQDiaDiem;
        private System.Windows.Forms.TextBox txtDTQDiaDiem;
        private System.Windows.Forms.Label lblCap_txtDTQNoiDung;
        private System.Windows.Forms.TextBox txtDTQNoiDung;
        private System.Windows.Forms.Label lblCap_txtDTQYNghia;
        private System.Windows.Forms.TextBox txtDTQYNghia;
        private System.Windows.Forms.Button btnThemDTQ;
    }
}
