namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyDoan
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.btnDong = new System.Windows.Forms.Button();
            this.grpDoan = new System.Windows.Forms.GroupBox();
            this.lblCap_txtMaDoan = new System.Windows.Forms.Label();
            this.txtMaDoan = new System.Windows.Forms.TextBox();
            this.lblCap_txtTenCQ = new System.Windows.Forms.Label();
            this.txtTenCQ = new System.Windows.Forms.TextBox();
            this.lblCap_txtDiaChi = new System.Windows.Forms.Label();
            this.txtDiaChi = new System.Windows.Forms.TextBox();
            this.lblCap_txtDT = new System.Windows.Forms.Label();
            this.txtDT = new System.Windows.Forms.TextBox();
            this.lblCap_txtDaiDien = new System.Windows.Forms.Label();
            this.txtDaiDien = new System.Windows.Forms.TextBox();
            this.grpDangKy = new System.Windows.Forms.GroupBox();
            this.lblCap_txtSo = new System.Windows.Forms.Label();
            this.txtSo = new System.Windows.Forms.TextBox();
            this.lblCap_cboTour = new System.Windows.Forms.Label();
            this.cboTour = new System.Windows.Forms.ComboBox();
            this.lblCap_dtDi = new System.Windows.Forms.Label();
            this.dtDi = new System.Windows.Forms.DateTimePicker();
            this.lblCap_numNguoi = new System.Windows.Forms.Label();
            this.numNguoi = new System.Windows.Forms.NumericUpDown();
            this.lblCap_txtDon = new System.Windows.Forms.Label();
            this.txtDon = new System.Windows.Forms.TextBox();
            this.lblCap_numCoc = new System.Windows.Forms.Label();
            this.numCoc = new System.Windows.Forms.NumericUpDown();
            this.chkBH = new System.Windows.Forms.CheckBox();
            this.lblCap_lblKetThuc = new System.Windows.Forms.Label();
            this.lblKetThuc = new System.Windows.Forms.Label();
            this.lblCap_lblTong = new System.Windows.Forms.Label();
            this.lblTong = new System.Windows.Forms.Label();
            this.dgvThanhVien = new System.Windows.Forms.DataGridView();
            this.btnDangKy = new System.Windows.Forms.Button();
            this.btnHuy = new System.Windows.Forms.Button();
            this.dgv = new System.Windows.Forms.DataGridView();
            this.pnlHeader.SuspendLayout();
            this.grpDoan.SuspendLayout();
            this.grpDangKy.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.SystemColors.Window;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Size = new System.Drawing.Size(1000, 56);
            this.pnlHeader.TabIndex = 0;
            this.pnlHeader.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblTitle.Text = "ĐĂNG KÝ THEO ĐOÀN";
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Regular);
            this.lblTitle.Location = new System.Drawing.Point(16, 13);
            this.lblTitle.TabIndex = 1;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Location = new System.Drawing.Point(884, 12);
            this.btnDong.Size = new System.Drawing.Size(100, 32);
            this.btnDong.TabIndex = 2;
            this.btnDong.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.grpDoan.Text = "Thông tin đoàn khách";
            this.lblCap_txtMaDoan.Text = "Mã đoàn:";
            this.lblCap_txtMaDoan.AutoSize = true;
            this.lblCap_txtMaDoan.Location = new System.Drawing.Point(14, 27);
            this.lblCap_txtMaDoan.TabIndex = 3;
            this.txtMaDoan.Location = new System.Drawing.Point(164, 22);
            this.txtMaDoan.Size = new System.Drawing.Size(296, 23);
            this.txtMaDoan.TabIndex = 4;
            this.lblCap_txtTenCQ.Text = "Cơ quan / gia đình:";
            this.lblCap_txtTenCQ.AutoSize = true;
            this.lblCap_txtTenCQ.Location = new System.Drawing.Point(484, 27);
            this.lblCap_txtTenCQ.TabIndex = 5;
            this.txtTenCQ.Location = new System.Drawing.Point(634, 22);
            this.txtTenCQ.Size = new System.Drawing.Size(296, 23);
            this.txtTenCQ.TabIndex = 6;
            this.lblCap_txtDiaChi.Text = "Địa chỉ:";
            this.lblCap_txtDiaChi.AutoSize = true;
            this.lblCap_txtDiaChi.Location = new System.Drawing.Point(14, 61);
            this.lblCap_txtDiaChi.TabIndex = 7;
            this.txtDiaChi.Location = new System.Drawing.Point(164, 56);
            this.txtDiaChi.Size = new System.Drawing.Size(790, 23);
            this.txtDiaChi.TabIndex = 8;
            this.lblCap_txtDT.Text = "Điện thoại:";
            this.lblCap_txtDT.AutoSize = true;
            this.lblCap_txtDT.Location = new System.Drawing.Point(14, 95);
            this.lblCap_txtDT.TabIndex = 9;
            this.txtDT.Location = new System.Drawing.Point(164, 90);
            this.txtDT.Size = new System.Drawing.Size(296, 23);
            this.txtDT.TabIndex = 10;
            this.lblCap_txtDaiDien.Text = "Người đại diện:";
            this.lblCap_txtDaiDien.AutoSize = true;
            this.lblCap_txtDaiDien.Location = new System.Drawing.Point(484, 95);
            this.lblCap_txtDaiDien.TabIndex = 11;
            this.txtDaiDien.Location = new System.Drawing.Point(634, 90);
            this.txtDaiDien.Size = new System.Drawing.Size(296, 23);
            this.txtDaiDien.TabIndex = 12;
            this.grpDoan.Location = new System.Drawing.Point(16, 70);
            this.grpDoan.Size = new System.Drawing.Size(968, 136);
            this.grpDoan.TabIndex = 13;
            this.grpDoan.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.grpDangKy.Text = "Đăng ký tour";
            this.lblCap_txtSo.Text = "Số phiếu:";
            this.lblCap_txtSo.AutoSize = true;
            this.lblCap_txtSo.Location = new System.Drawing.Point(14, 27);
            this.lblCap_txtSo.TabIndex = 14;
            this.txtSo.Location = new System.Drawing.Point(164, 22);
            this.txtSo.Size = new System.Drawing.Size(296, 23);
            this.txtSo.TabIndex = 15;
            this.lblCap_cboTour.Text = "Tour:";
            this.lblCap_cboTour.AutoSize = true;
            this.lblCap_cboTour.Location = new System.Drawing.Point(484, 27);
            this.lblCap_cboTour.TabIndex = 16;
            this.cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTour.FormattingEnabled = true;
            this.cboTour.Location = new System.Drawing.Point(634, 22);
            this.cboTour.Size = new System.Drawing.Size(296, 23);
            this.cboTour.TabIndex = 17;
            this.lblCap_dtDi.Text = "Ngày đi:";
            this.lblCap_dtDi.AutoSize = true;
            this.lblCap_dtDi.Location = new System.Drawing.Point(14, 61);
            this.lblCap_dtDi.TabIndex = 18;
            this.dtDi.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtDi.Location = new System.Drawing.Point(164, 56);
            this.dtDi.Size = new System.Drawing.Size(180, 23);
            this.dtDi.TabIndex = 19;
            this.lblCap_numNguoi.Text = "Số người:";
            this.lblCap_numNguoi.AutoSize = true;
            this.lblCap_numNguoi.Location = new System.Drawing.Point(484, 61);
            this.lblCap_numNguoi.TabIndex = 20;
            this.numNguoi.Minimum = new decimal(new int[] {13, 0, 0, 0});
            this.numNguoi.Maximum = new decimal(new int[] {1000, 0, 0, 0});
            this.numNguoi.Value = new decimal(new int[] {13, 0, 0, 0});
            this.numNguoi.Location = new System.Drawing.Point(634, 56);
            this.numNguoi.Size = new System.Drawing.Size(180, 23);
            this.numNguoi.TabIndex = 21;
            this.lblCap_txtDon.Text = "Địa điểm đón:";
            this.lblCap_txtDon.AutoSize = true;
            this.lblCap_txtDon.Location = new System.Drawing.Point(14, 95);
            this.lblCap_txtDon.TabIndex = 22;
            this.txtDon.Location = new System.Drawing.Point(164, 90);
            this.txtDon.Size = new System.Drawing.Size(790, 23);
            this.txtDon.TabIndex = 23;
            this.lblCap_numCoc.Text = "Tiền cọc:";
            this.lblCap_numCoc.AutoSize = true;
            this.lblCap_numCoc.Location = new System.Drawing.Point(14, 129);
            this.lblCap_numCoc.TabIndex = 24;
            this.numCoc.Minimum = new decimal(new int[] {0, 0, 0, 0});
            this.numCoc.Maximum = new decimal(new int[] {2000000000, 0, 0, 0});
            this.numCoc.Increment = new decimal(new int[] {100000, 0, 0, 0});
            this.numCoc.ThousandsSeparator = true;
            this.numCoc.Value = new decimal(new int[] {0, 0, 0, 0});
            this.numCoc.Location = new System.Drawing.Point(164, 124);
            this.numCoc.Size = new System.Drawing.Size(180, 23);
            this.numCoc.TabIndex = 25;
            this.chkBH.Text = "Mua bảo hiểm";
            this.chkBH.AutoSize = true;
            this.chkBH.UseVisualStyleBackColor = true;
            this.chkBH.Location = new System.Drawing.Point(634, 128);
            this.chkBH.TabIndex = 26;
            this.lblCap_lblKetThuc.Text = "Kết thúc DK:";
            this.lblCap_lblKetThuc.AutoSize = true;
            this.lblCap_lblKetThuc.Location = new System.Drawing.Point(14, 163);
            this.lblCap_lblKetThuc.TabIndex = 27;
            this.lblKetThuc.Text = "-";
            this.lblKetThuc.AutoSize = true;
            this.lblKetThuc.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular);
            this.lblKetThuc.Location = new System.Drawing.Point(164, 162);
            this.lblKetThuc.TabIndex = 28;
            this.lblCap_lblTong.Text = "Tổng dự kiến:";
            this.lblCap_lblTong.AutoSize = true;
            this.lblCap_lblTong.Location = new System.Drawing.Point(484, 163);
            this.lblCap_lblTong.TabIndex = 29;
            this.lblTong.Text = "-";
            this.lblTong.AutoSize = true;
            this.lblTong.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular);
            this.lblTong.Location = new System.Drawing.Point(634, 162);
            this.lblTong.TabIndex = 30;
            this.grpDangKy.Location = new System.Drawing.Point(16, 218);
            this.grpDangKy.Size = new System.Drawing.Size(968, 204);
            this.grpDangKy.TabIndex = 31;
            this.grpDangKy.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.dgvThanhVien.AllowUserToAddRows = true;
            this.dgvThanhVien.AllowUserToDeleteRows = true;
            this.dgvThanhVien.ReadOnly = false;
            this.dgvThanhVien.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvThanhVien.MultiSelect = false;
            this.dgvThanhVien.RowHeadersVisible = false;
            this.dgvThanhVien.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvThanhVien.BackgroundColor = System.Drawing.Color.White;
            this.dgvThanhVien.Location = new System.Drawing.Point(16, 434);
            this.dgvThanhVien.Size = new System.Drawing.Size(968, 104);
            this.dgvThanhVien.TabIndex = 32;
            this.dgvThanhVien.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.btnDangKy.Text = "Lập phiếu đăng ký";
            this.btnDangKy.UseVisualStyleBackColor = true;
            this.btnDangKy.Location = new System.Drawing.Point(16, 550);
            this.btnDangKy.Size = new System.Drawing.Size(185, 36);
            this.btnDangKy.TabIndex = 33;
            this.btnHuy.Text = "Hủy phiếu (mất cọc)";
            this.btnHuy.UseVisualStyleBackColor = true;
            this.btnHuy.Location = new System.Drawing.Point(211, 550);
            this.btnHuy.Size = new System.Drawing.Size(203, 36);
            this.btnHuy.TabIndex = 34;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.ReadOnly = true;
            this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.RowHeadersVisible = false;
            this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv.BackgroundColor = System.Drawing.Color.White;
            this.dgv.Location = new System.Drawing.Point(16, 598);
            this.dgv.Size = new System.Drawing.Size(968, 170);
            this.dgv.TabIndex = 35;
            this.dgv.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.pnlHeader.Controls.Add(this.lblTitle);
            this.pnlHeader.Controls.Add(this.btnDong);
            this.Controls.Add(this.pnlHeader);
            this.grpDoan.Controls.Add(this.lblCap_txtMaDoan);
            this.grpDoan.Controls.Add(this.txtMaDoan);
            this.grpDoan.Controls.Add(this.lblCap_txtTenCQ);
            this.grpDoan.Controls.Add(this.txtTenCQ);
            this.grpDoan.Controls.Add(this.lblCap_txtDiaChi);
            this.grpDoan.Controls.Add(this.txtDiaChi);
            this.grpDoan.Controls.Add(this.lblCap_txtDT);
            this.grpDoan.Controls.Add(this.txtDT);
            this.grpDoan.Controls.Add(this.lblCap_txtDaiDien);
            this.grpDoan.Controls.Add(this.txtDaiDien);
            this.Controls.Add(this.grpDoan);
            this.grpDangKy.Controls.Add(this.lblCap_txtSo);
            this.grpDangKy.Controls.Add(this.txtSo);
            this.grpDangKy.Controls.Add(this.lblCap_cboTour);
            this.grpDangKy.Controls.Add(this.cboTour);
            this.grpDangKy.Controls.Add(this.lblCap_dtDi);
            this.grpDangKy.Controls.Add(this.dtDi);
            this.grpDangKy.Controls.Add(this.lblCap_numNguoi);
            this.grpDangKy.Controls.Add(this.numNguoi);
            this.grpDangKy.Controls.Add(this.lblCap_txtDon);
            this.grpDangKy.Controls.Add(this.txtDon);
            this.grpDangKy.Controls.Add(this.lblCap_numCoc);
            this.grpDangKy.Controls.Add(this.numCoc);
            this.grpDangKy.Controls.Add(this.chkBH);
            this.grpDangKy.Controls.Add(this.lblCap_lblKetThuc);
            this.grpDangKy.Controls.Add(this.lblKetThuc);
            this.grpDangKy.Controls.Add(this.lblCap_lblTong);
            this.grpDangKy.Controls.Add(this.lblTong);
            this.Controls.Add(this.grpDangKy);
            this.Controls.Add(this.dgvThanhVien);
            this.Controls.Add(this.btnDangKy);
            this.Controls.Add(this.btnHuy);
            this.Controls.Add(this.dgv);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(1000, 740);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "FrmDangKyDoan";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Đăng ký theo đoàn";
            this.AutoScroll = true;
            this.cboTour.SelectedIndexChanged += new System.EventHandler(this.TinhTong);
            this.dtDi.ValueChanged += new System.EventHandler(this.TinhTong);
            this.numNguoi.ValueChanged += new System.EventHandler(this.TinhTong);
            this.chkBH.CheckedChanged += new System.EventHandler(this.chkBH_CheckedChanged);
            this.cboTour.SelectedIndexChanged += new System.EventHandler(this.TinhTong);
            this.dtDi.ValueChanged += new System.EventHandler(this.TinhTong);
            this.numNguoi.ValueChanged += new System.EventHandler(this.TinhTong);
            this.chkBH.CheckedChanged += new System.EventHandler(this.chkBH_CheckedChanged);
            this.btnDangKy.Click += new System.EventHandler(this.btnDangKy_Click);
            this.btnHuy.Click += new System.EventHandler(this.btnHuy_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Load += new System.EventHandler(this.FrmDangKyDoan_Load);
            this.pnlHeader.ResumeLayout(false);
            this.grpDoan.ResumeLayout(false);
            this.grpDangKy.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.GroupBox grpDoan;
        private System.Windows.Forms.Label lblCap_txtMaDoan;
        private System.Windows.Forms.TextBox txtMaDoan;
        private System.Windows.Forms.Label lblCap_txtTenCQ;
        private System.Windows.Forms.TextBox txtTenCQ;
        private System.Windows.Forms.Label lblCap_txtDiaChi;
        private System.Windows.Forms.TextBox txtDiaChi;
        private System.Windows.Forms.Label lblCap_txtDT;
        private System.Windows.Forms.TextBox txtDT;
        private System.Windows.Forms.Label lblCap_txtDaiDien;
        private System.Windows.Forms.TextBox txtDaiDien;
        private System.Windows.Forms.GroupBox grpDangKy;
        private System.Windows.Forms.Label lblCap_txtSo;
        private System.Windows.Forms.TextBox txtSo;
        private System.Windows.Forms.Label lblCap_cboTour;
        private System.Windows.Forms.ComboBox cboTour;
        private System.Windows.Forms.Label lblCap_dtDi;
        private System.Windows.Forms.DateTimePicker dtDi;
        private System.Windows.Forms.Label lblCap_numNguoi;
        private System.Windows.Forms.NumericUpDown numNguoi;
        private System.Windows.Forms.Label lblCap_txtDon;
        private System.Windows.Forms.TextBox txtDon;
        private System.Windows.Forms.Label lblCap_numCoc;
        private System.Windows.Forms.NumericUpDown numCoc;
        private System.Windows.Forms.CheckBox chkBH;
        private System.Windows.Forms.Label lblCap_lblKetThuc;
        private System.Windows.Forms.Label lblKetThuc;
        private System.Windows.Forms.Label lblCap_lblTong;
        private System.Windows.Forms.Label lblTong;
        private System.Windows.Forms.DataGridView dgvThanhVien;
        private System.Windows.Forms.Button btnDangKy;
        private System.Windows.Forms.Button btnHuy;
        private System.Windows.Forms.DataGridView dgv;
    }
}
