namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmKetThucKhaoSat
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.btnDong = new System.Windows.Forms.Button();
            this.tabKT = new System.Windows.Forms.TabControl();
            this.tp1 = new System.Windows.Forms.TabPage();
            this.tp2 = new System.Windows.Forms.TabPage();
            this.dgvDoan = new System.Windows.Forms.DataGridView();
            this.lblCap_txtSoTT = new System.Windows.Forms.Label();
            this.txtSoTT = new System.Windows.Forms.TextBox();
            this.lblCap_txtSoDK = new System.Windows.Forms.Label();
            this.txtSoDK = new System.Windows.Forms.TextBox();
            this.lblCap_dtTT = new System.Windows.Forms.Label();
            this.dtTT = new System.Windows.Forms.DateTimePicker();
            this.lblCap_numTien = new System.Windows.Forms.Label();
            this.numTien = new System.Windows.Forms.NumericUpDown();
            this.lblCap_txtGhiChu = new System.Windows.Forms.Label();
            this.txtGhiChu = new System.Windows.Forms.TextBox();
            this.btnThanhToan = new System.Windows.Forms.Button();
            this.lblCap_cboLoaiKS = new System.Windows.Forms.Label();
            this.cboLoaiKS = new System.Windows.Forms.ComboBox();
            this.lblCap_cboDangKy = new System.Windows.Forms.Label();
            this.cboDangKy = new System.Windows.Forms.ComboBox();
            this.lblCap_txtMaKS = new System.Windows.Forms.Label();
            this.txtMaKS = new System.Windows.Forms.TextBox();
            this.lblCap_dtGui = new System.Windows.Forms.Label();
            this.dtGui = new System.Windows.Forms.DateTimePicker();
            this.btnGui = new System.Windows.Forms.Button();
            this.dgvKS = new System.Windows.Forms.DataGridView();
            this.lblCap_txtKSChon = new System.Windows.Forms.Label();
            this.txtKSChon = new System.Windows.Forms.TextBox();
            this.lblCap_dtPH = new System.Windows.Forms.Label();
            this.dtPH = new System.Windows.Forms.DateTimePicker();
            this.lblCap_numDiem = new System.Windows.Forms.Label();
            this.numDiem = new System.Windows.Forms.NumericUpDown();
            this.lblCap_txtGopY = new System.Windows.Forms.Label();
            this.txtGopY = new System.Windows.Forms.TextBox();
            this.btnGhiPH = new System.Windows.Forms.Button();
            this.pnlHeader.SuspendLayout();
            this.tabKT.SuspendLayout();
            this.tp1.SuspendLayout();
            this.tp2.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.SystemColors.Window;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Size = new System.Drawing.Size(1000, 56);
            this.pnlHeader.TabIndex = 0;
            this.pnlHeader.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblTitle.Text = "KẾT THÚC TOUR - KHẢO SÁT";
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Regular);
            this.lblTitle.Location = new System.Drawing.Point(16, 13);
            this.lblTitle.TabIndex = 1;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Location = new System.Drawing.Point(884, 12);
            this.btnDong.Size = new System.Drawing.Size(100, 32);
            this.btnDong.TabIndex = 2;
            this.btnDong.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.dgvDoan.AllowUserToAddRows = false;
            this.dgvDoan.AllowUserToDeleteRows = false;
            this.dgvDoan.ReadOnly = true;
            this.dgvDoan.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDoan.MultiSelect = false;
            this.dgvDoan.RowHeadersVisible = false;
            this.dgvDoan.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDoan.BackgroundColor = System.Drawing.Color.White;
            this.dgvDoan.Location = new System.Drawing.Point(10, 8);
            this.dgvDoan.Size = new System.Drawing.Size(940, 170);
            this.dgvDoan.TabIndex = 3;
            this.dgvDoan.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_txtSoTT.Text = "Số thanh toán:";
            this.lblCap_txtSoTT.AutoSize = true;
            this.lblCap_txtSoTT.Location = new System.Drawing.Point(14, 195);
            this.lblCap_txtSoTT.TabIndex = 4;
            this.txtSoTT.Location = new System.Drawing.Point(164, 190);
            this.txtSoTT.Size = new System.Drawing.Size(292, 23);
            this.txtSoTT.TabIndex = 5;
            this.lblCap_txtSoDK.Text = "Phiếu đoàn:";
            this.lblCap_txtSoDK.AutoSize = true;
            this.lblCap_txtSoDK.Location = new System.Drawing.Point(480, 195);
            this.lblCap_txtSoDK.TabIndex = 6;
            this.txtSoDK.Location = new System.Drawing.Point(630, 190);
            this.txtSoDK.Size = new System.Drawing.Size(292, 23);
            this.txtSoDK.TabIndex = 7;
            this.lblCap_dtTT.Text = "Ngày thanh toán:";
            this.lblCap_dtTT.AutoSize = true;
            this.lblCap_dtTT.Location = new System.Drawing.Point(14, 229);
            this.lblCap_dtTT.TabIndex = 8;
            this.dtTT.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtTT.Location = new System.Drawing.Point(164, 224);
            this.dtTT.Size = new System.Drawing.Size(180, 23);
            this.dtTT.TabIndex = 9;
            this.lblCap_numTien.Text = "Số tiền:";
            this.lblCap_numTien.AutoSize = true;
            this.lblCap_numTien.Location = new System.Drawing.Point(480, 229);
            this.lblCap_numTien.TabIndex = 10;
            this.numTien.Minimum = new decimal(new int[] {0, 0, 0, 0});
            this.numTien.Maximum = new decimal(new int[] {2000000000, 0, 0, 0});
            this.numTien.Increment = new decimal(new int[] {100000, 0, 0, 0});
            this.numTien.ThousandsSeparator = true;
            this.numTien.Value = new decimal(new int[] {0, 0, 0, 0});
            this.numTien.Location = new System.Drawing.Point(630, 224);
            this.numTien.Size = new System.Drawing.Size(180, 23);
            this.numTien.TabIndex = 11;
            this.lblCap_txtGhiChu.Text = "Ghi chú:";
            this.lblCap_txtGhiChu.AutoSize = true;
            this.lblCap_txtGhiChu.Location = new System.Drawing.Point(14, 263);
            this.lblCap_txtGhiChu.TabIndex = 12;
            this.txtGhiChu.Location = new System.Drawing.Point(164, 258);
            this.txtGhiChu.Size = new System.Drawing.Size(782, 23);
            this.txtGhiChu.TabIndex = 13;
            this.btnThanhToan.Text = "Ghi nhận thanh toán";
            this.btnThanhToan.UseVisualStyleBackColor = true;
            this.btnThanhToan.Location = new System.Drawing.Point(10, 298);
            this.btnThanhToan.Size = new System.Drawing.Size(203, 36);
            this.btnThanhToan.TabIndex = 14;
            this.lblCap_cboLoaiKS.Text = "Loại khách:";
            this.lblCap_cboLoaiKS.AutoSize = true;
            this.lblCap_cboLoaiKS.Location = new System.Drawing.Point(14, 13);
            this.lblCap_cboLoaiKS.TabIndex = 15;
            this.cboLoaiKS.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLoaiKS.FormattingEnabled = true;
            this.cboLoaiKS.Location = new System.Drawing.Point(164, 8);
            this.cboLoaiKS.Size = new System.Drawing.Size(292, 23);
            this.cboLoaiKS.TabIndex = 16;
            this.lblCap_cboDangKy.Text = "Đăng ký đã kết thúc:";
            this.lblCap_cboDangKy.AutoSize = true;
            this.lblCap_cboDangKy.Location = new System.Drawing.Point(480, 13);
            this.lblCap_cboDangKy.TabIndex = 17;
            this.cboDangKy.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDangKy.FormattingEnabled = true;
            this.cboDangKy.Location = new System.Drawing.Point(630, 8);
            this.cboDangKy.Size = new System.Drawing.Size(292, 23);
            this.cboDangKy.TabIndex = 18;
            this.lblCap_txtMaKS.Text = "Mã KS:";
            this.lblCap_txtMaKS.AutoSize = true;
            this.lblCap_txtMaKS.Location = new System.Drawing.Point(14, 47);
            this.lblCap_txtMaKS.TabIndex = 19;
            this.txtMaKS.Location = new System.Drawing.Point(164, 42);
            this.txtMaKS.Size = new System.Drawing.Size(292, 23);
            this.txtMaKS.TabIndex = 20;
            this.lblCap_dtGui.Text = "Ngày gửi:";
            this.lblCap_dtGui.AutoSize = true;
            this.lblCap_dtGui.Location = new System.Drawing.Point(480, 47);
            this.lblCap_dtGui.TabIndex = 21;
            this.dtGui.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtGui.Location = new System.Drawing.Point(630, 42);
            this.dtGui.Size = new System.Drawing.Size(180, 23);
            this.dtGui.TabIndex = 22;
            this.btnGui.Text = "Gửi phiếu khảo sát";
            this.btnGui.UseVisualStyleBackColor = true;
            this.btnGui.Location = new System.Drawing.Point(10, 82);
            this.btnGui.Size = new System.Drawing.Size(194, 36);
            this.btnGui.TabIndex = 23;
            this.dgvKS.AllowUserToAddRows = false;
            this.dgvKS.AllowUserToDeleteRows = false;
            this.dgvKS.ReadOnly = true;
            this.dgvKS.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvKS.MultiSelect = false;
            this.dgvKS.RowHeadersVisible = false;
            this.dgvKS.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvKS.BackgroundColor = System.Drawing.Color.White;
            this.dgvKS.Location = new System.Drawing.Point(10, 130);
            this.dgvKS.Size = new System.Drawing.Size(940, 170);
            this.dgvKS.TabIndex = 24;
            this.dgvKS.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_txtKSChon.Text = "Phiếu chọn:";
            this.lblCap_txtKSChon.AutoSize = true;
            this.lblCap_txtKSChon.Location = new System.Drawing.Point(14, 317);
            this.lblCap_txtKSChon.TabIndex = 25;
            this.txtKSChon.Location = new System.Drawing.Point(164, 312);
            this.txtKSChon.Size = new System.Drawing.Size(292, 23);
            this.txtKSChon.TabIndex = 26;
            this.lblCap_dtPH.Text = "Ngày phản hồi:";
            this.lblCap_dtPH.AutoSize = true;
            this.lblCap_dtPH.Location = new System.Drawing.Point(480, 317);
            this.lblCap_dtPH.TabIndex = 27;
            this.dtPH.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtPH.Location = new System.Drawing.Point(630, 312);
            this.dtPH.Size = new System.Drawing.Size(180, 23);
            this.dtPH.TabIndex = 28;
            this.lblCap_numDiem.Text = "Điểm (1-5):";
            this.lblCap_numDiem.AutoSize = true;
            this.lblCap_numDiem.Location = new System.Drawing.Point(14, 351);
            this.lblCap_numDiem.TabIndex = 29;
            this.numDiem.Minimum = new decimal(new int[] {1, 0, 0, 0});
            this.numDiem.Maximum = new decimal(new int[] {5, 0, 0, 0});
            this.numDiem.Value = new decimal(new int[] {5, 0, 0, 0});
            this.numDiem.Location = new System.Drawing.Point(164, 346);
            this.numDiem.Size = new System.Drawing.Size(180, 23);
            this.numDiem.TabIndex = 30;
            this.lblCap_txtGopY.Text = "Góp ý:";
            this.lblCap_txtGopY.AutoSize = true;
            this.lblCap_txtGopY.Location = new System.Drawing.Point(14, 385);
            this.lblCap_txtGopY.TabIndex = 31;
            this.txtGopY.Multiline = true;
            this.txtGopY.Location = new System.Drawing.Point(164, 380);
            this.txtGopY.Size = new System.Drawing.Size(782, 56);
            this.txtGopY.TabIndex = 32;
            this.btnGhiPH.Text = "Ghi nhận góp ý";
            this.btnGhiPH.UseVisualStyleBackColor = true;
            this.btnGhiPH.Location = new System.Drawing.Point(10, 450);
            this.btnGhiPH.Size = new System.Drawing.Size(158, 36);
            this.btnGhiPH.TabIndex = 33;
            this.tp1.Text = "Thanh toán sau tour (đoàn)";
            this.tp1.UseVisualStyleBackColor = true;
            this.tp1.Location = new System.Drawing.Point(4, 26);
            this.tp1.Size = new System.Drawing.Size(960, 504);
            this.tp1.TabIndex = 34;
            this.tp2.Text = "Khảo sát khách hàng";
            this.tp2.UseVisualStyleBackColor = true;
            this.tp2.Location = new System.Drawing.Point(4, 26);
            this.tp2.Size = new System.Drawing.Size(960, 504);
            this.tp2.TabIndex = 35;
            this.tabKT.Location = new System.Drawing.Point(16, 70);
            this.tabKT.Size = new System.Drawing.Size(968, 536);
            this.tabKT.TabIndex = 36;
            this.tabKT.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.pnlHeader.Controls.Add(this.lblTitle);
            this.pnlHeader.Controls.Add(this.btnDong);
            this.Controls.Add(this.pnlHeader);
            this.tp1.Controls.Add(this.dgvDoan);
            this.tp1.Controls.Add(this.lblCap_txtSoTT);
            this.tp1.Controls.Add(this.txtSoTT);
            this.tp1.Controls.Add(this.lblCap_txtSoDK);
            this.tp1.Controls.Add(this.txtSoDK);
            this.tp1.Controls.Add(this.lblCap_dtTT);
            this.tp1.Controls.Add(this.dtTT);
            this.tp1.Controls.Add(this.lblCap_numTien);
            this.tp1.Controls.Add(this.numTien);
            this.tp1.Controls.Add(this.lblCap_txtGhiChu);
            this.tp1.Controls.Add(this.txtGhiChu);
            this.tp1.Controls.Add(this.btnThanhToan);
            this.tp2.Controls.Add(this.lblCap_cboLoaiKS);
            this.tp2.Controls.Add(this.cboLoaiKS);
            this.tp2.Controls.Add(this.lblCap_cboDangKy);
            this.tp2.Controls.Add(this.cboDangKy);
            this.tp2.Controls.Add(this.lblCap_txtMaKS);
            this.tp2.Controls.Add(this.txtMaKS);
            this.tp2.Controls.Add(this.lblCap_dtGui);
            this.tp2.Controls.Add(this.dtGui);
            this.tp2.Controls.Add(this.btnGui);
            this.tp2.Controls.Add(this.dgvKS);
            this.tp2.Controls.Add(this.lblCap_txtKSChon);
            this.tp2.Controls.Add(this.txtKSChon);
            this.tp2.Controls.Add(this.lblCap_dtPH);
            this.tp2.Controls.Add(this.dtPH);
            this.tp2.Controls.Add(this.lblCap_numDiem);
            this.tp2.Controls.Add(this.numDiem);
            this.tp2.Controls.Add(this.lblCap_txtGopY);
            this.tp2.Controls.Add(this.txtGopY);
            this.tp2.Controls.Add(this.btnGhiPH);
            this.tabKT.Controls.Add(this.tp1);
            this.tabKT.Controls.Add(this.tp2);
            this.Controls.Add(this.tabKT);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(1000, 622);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "FrmKetThucKhaoSat";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Kết thúc tour - khảo sát";
            this.AutoScroll = true;
            this.dgvDoan.SelectionChanged += new System.EventHandler(this.dgvDoan_SelectionChanged);
            this.btnThanhToan.Click += new System.EventHandler(this.btnThanhToan_Click);
            this.cboLoaiKS.SelectedIndexChanged += new System.EventHandler(this.cboLoaiKS_SelectedIndexChanged);
            this.btnGui.Click += new System.EventHandler(this.btnGui_Click);
            this.dgvKS.SelectionChanged += new System.EventHandler(this.dgvKS_SelectionChanged);
            this.btnGhiPH.Click += new System.EventHandler(this.btnGhiPH_Click);
            this.dgvDoan.SelectionChanged += new System.EventHandler(this.dgvDoan_SelectionChanged);
            this.btnThanhToan.Click += new System.EventHandler(this.btnThanhToan_Click);
            this.cboLoaiKS.SelectedIndexChanged += new System.EventHandler(this.cboLoaiKS_SelectedIndexChanged);
            this.btnGui.Click += new System.EventHandler(this.btnGui_Click);
            this.dgvKS.SelectionChanged += new System.EventHandler(this.dgvKS_SelectionChanged);
            this.btnGhiPH.Click += new System.EventHandler(this.btnGhiPH_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Load += new System.EventHandler(this.FrmKetThucKhaoSat_Load);
            this.pnlHeader.ResumeLayout(false);
            this.tabKT.ResumeLayout(false);
            this.tp1.ResumeLayout(false);
            this.tp2.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.TabControl tabKT;
        private System.Windows.Forms.TabPage tp1;
        private System.Windows.Forms.TabPage tp2;
        private System.Windows.Forms.DataGridView dgvDoan;
        private System.Windows.Forms.Label lblCap_txtSoTT;
        private System.Windows.Forms.TextBox txtSoTT;
        private System.Windows.Forms.Label lblCap_txtSoDK;
        private System.Windows.Forms.TextBox txtSoDK;
        private System.Windows.Forms.Label lblCap_dtTT;
        private System.Windows.Forms.DateTimePicker dtTT;
        private System.Windows.Forms.Label lblCap_numTien;
        private System.Windows.Forms.NumericUpDown numTien;
        private System.Windows.Forms.Label lblCap_txtGhiChu;
        private System.Windows.Forms.TextBox txtGhiChu;
        private System.Windows.Forms.Button btnThanhToan;
        private System.Windows.Forms.Label lblCap_cboLoaiKS;
        private System.Windows.Forms.ComboBox cboLoaiKS;
        private System.Windows.Forms.Label lblCap_cboDangKy;
        private System.Windows.Forms.ComboBox cboDangKy;
        private System.Windows.Forms.Label lblCap_txtMaKS;
        private System.Windows.Forms.TextBox txtMaKS;
        private System.Windows.Forms.Label lblCap_dtGui;
        private System.Windows.Forms.DateTimePicker dtGui;
        private System.Windows.Forms.Button btnGui;
        private System.Windows.Forms.DataGridView dgvKS;
        private System.Windows.Forms.Label lblCap_txtKSChon;
        private System.Windows.Forms.TextBox txtKSChon;
        private System.Windows.Forms.Label lblCap_dtPH;
        private System.Windows.Forms.DateTimePicker dtPH;
        private System.Windows.Forms.Label lblCap_numDiem;
        private System.Windows.Forms.NumericUpDown numDiem;
        private System.Windows.Forms.Label lblCap_txtGopY;
        private System.Windows.Forms.TextBox txtGopY;
        private System.Windows.Forms.Button btnGhiPH;
    }
}
