namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmTour
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.btnDong = new System.Windows.Forms.Button();
            this.pnlCard1 = new System.Windows.Forms.Panel();
            this.lblCap_cboTour = new System.Windows.Forms.Label();
            this.cboTour = new System.Windows.Forms.ComboBox();
            this.tabTour = new System.Windows.Forms.TabControl();
            this.tp1 = new System.Windows.Forms.TabPage();
            this.tp2 = new System.Windows.Forms.TabPage();
            this.tp3 = new System.Windows.Forms.TabPage();
            this.tp4 = new System.Windows.Forms.TabPage();
            this.dgvTour = new System.Windows.Forms.DataGridView();
            this.lblCap_txtMa = new System.Windows.Forms.Label();
            this.txtMa = new System.Windows.Forms.TextBox();
            this.lblCap_txtTen = new System.Windows.Forms.Label();
            this.txtTen = new System.Windows.Forms.TextBox();
            this.lblCap_numNgay = new System.Windows.Forms.Label();
            this.numNgay = new System.Windows.Forms.NumericUpDown();
            this.lblCap_numDem = new System.Windows.Forms.Label();
            this.numDem = new System.Windows.Forms.NumericUpDown();
            this.lblCap_numGia = new System.Windows.Forms.Label();
            this.numGia = new System.Windows.Forms.NumericUpDown();
            this.lblCap_txtMoTa = new System.Windows.Forms.Label();
            this.txtMoTa = new System.Windows.Forms.TextBox();
            this.btnThemTour = new System.Windows.Forms.Button();
            this.dgvDiemDung = new System.Windows.Forms.DataGridView();
            this.lblCap_numThuTu = new System.Windows.Forms.Label();
            this.numThuTu = new System.Windows.Forms.NumericUpDown();
            this.lblCap_txtDiemDung = new System.Windows.Forms.Label();
            this.txtDiemDung = new System.Windows.Forms.TextBox();
            this.chkDoiPT = new System.Windows.Forms.CheckBox();
            this.chkAn = new System.Windows.Forms.CheckBox();
            this.chkKS = new System.Windows.Forms.CheckBox();
            this.lblCap_numSao = new System.Windows.Forms.Label();
            this.numSao = new System.Windows.Forms.NumericUpDown();
            this.lblCap_txtGhiChuDD = new System.Windows.Forms.Label();
            this.txtGhiChuDD = new System.Windows.Forms.TextBox();
            this.btnThemDD = new System.Windows.Forms.Button();
            this.dgvChang = new System.Windows.Forms.DataGridView();
            this.lblCap_numChang = new System.Windows.Forms.Label();
            this.numChang = new System.Windows.Forms.NumericUpDown();
            this.lblCap_cboPT = new System.Windows.Forms.Label();
            this.cboPT = new System.Windows.Forms.ComboBox();
            this.lblCap_txtGhiChuPT = new System.Windows.Forms.Label();
            this.txtGhiChuPT = new System.Windows.Forms.TextBox();
            this.btnThemChang = new System.Windows.Forms.Button();
            this.dgvTQ = new System.Windows.Forms.DataGridView();
            this.lblCap_cboDTQ = new System.Windows.Forms.Label();
            this.cboDTQ = new System.Windows.Forms.ComboBox();
            this.lblCap_numThuTuTQ = new System.Windows.Forms.Label();
            this.numThuTuTQ = new System.Windows.Forms.NumericUpDown();
            this.btnThemTQ = new System.Windows.Forms.Button();
            this.pnlHeader.SuspendLayout();
            this.pnlCard1.SuspendLayout();
            this.tabTour.SuspendLayout();
            this.tp1.SuspendLayout();
            this.tp2.SuspendLayout();
            this.tp3.SuspendLayout();
            this.tp4.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.SystemColors.Window;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Size = new System.Drawing.Size(980, 56);
            this.pnlHeader.TabIndex = 0;
            this.pnlHeader.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblTitle.Text = "TOUR - HÀNH TRÌNH";
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Regular);
            this.lblTitle.Location = new System.Drawing.Point(16, 13);
            this.lblTitle.TabIndex = 1;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.btnDong.Location = new System.Drawing.Point(864, 12);
            this.btnDong.Size = new System.Drawing.Size(100, 32);
            this.btnDong.TabIndex = 2;
            this.btnDong.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_cboTour.Text = "Tour đang chọn:";
            this.lblCap_cboTour.AutoSize = true;
            this.lblCap_cboTour.Location = new System.Drawing.Point(14, 17);
            this.lblCap_cboTour.TabIndex = 3;
            this.cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTour.FormattingEnabled = true;
            this.cboTour.Location = new System.Drawing.Point(164, 12);
            this.cboTour.Size = new System.Drawing.Size(286, 23);
            this.cboTour.TabIndex = 4;
            this.pnlCard1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlCard1.Location = new System.Drawing.Point(16, 70);
            this.pnlCard1.Size = new System.Drawing.Size(948, 54);
            this.pnlCard1.TabIndex = 5;
            this.pnlCard1.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.dgvTour.AllowUserToAddRows = false;
            this.dgvTour.AllowUserToDeleteRows = false;
            this.dgvTour.ReadOnly = true;
            this.dgvTour.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvTour.MultiSelect = false;
            this.dgvTour.RowHeadersVisible = false;
            this.dgvTour.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTour.BackgroundColor = System.Drawing.Color.White;
            this.dgvTour.Location = new System.Drawing.Point(10, 8);
            this.dgvTour.Size = new System.Drawing.Size(920, 170);
            this.dgvTour.TabIndex = 6;
            this.dgvTour.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_txtMa.Text = "Mã tour:";
            this.lblCap_txtMa.AutoSize = true;
            this.lblCap_txtMa.Location = new System.Drawing.Point(14, 195);
            this.lblCap_txtMa.TabIndex = 7;
            this.txtMa.Location = new System.Drawing.Point(164, 190);
            this.txtMa.Size = new System.Drawing.Size(282, 23);
            this.txtMa.TabIndex = 8;
            this.lblCap_txtTen.Text = "Tên tour:";
            this.lblCap_txtTen.AutoSize = true;
            this.lblCap_txtTen.Location = new System.Drawing.Point(470, 195);
            this.lblCap_txtTen.TabIndex = 9;
            this.txtTen.Location = new System.Drawing.Point(620, 190);
            this.txtTen.Size = new System.Drawing.Size(282, 23);
            this.txtTen.TabIndex = 10;
            this.lblCap_numNgay.Text = "Số ngày:";
            this.lblCap_numNgay.AutoSize = true;
            this.lblCap_numNgay.Location = new System.Drawing.Point(14, 229);
            this.lblCap_numNgay.TabIndex = 11;
            this.numNgay.Minimum = new decimal(new int[] {1, 0, 0, 0});
            this.numNgay.Maximum = new decimal(new int[] {30, 0, 0, 0});
            this.numNgay.Value = new decimal(new int[] {1, 0, 0, 0});
            this.numNgay.Location = new System.Drawing.Point(164, 224);
            this.numNgay.Size = new System.Drawing.Size(180, 23);
            this.numNgay.TabIndex = 12;
            this.lblCap_numDem.Text = "Số đêm:";
            this.lblCap_numDem.AutoSize = true;
            this.lblCap_numDem.Location = new System.Drawing.Point(470, 229);
            this.lblCap_numDem.TabIndex = 13;
            this.numDem.Minimum = new decimal(new int[] {0, 0, 0, 0});
            this.numDem.Maximum = new decimal(new int[] {30, 0, 0, 0});
            this.numDem.Value = new decimal(new int[] {0, 0, 0, 0});
            this.numDem.Location = new System.Drawing.Point(620, 224);
            this.numDem.Size = new System.Drawing.Size(180, 23);
            this.numDem.TabIndex = 14;
            this.lblCap_numGia.Text = "Đơn giá / khách:";
            this.lblCap_numGia.AutoSize = true;
            this.lblCap_numGia.Location = new System.Drawing.Point(14, 263);
            this.lblCap_numGia.TabIndex = 15;
            this.numGia.Minimum = new decimal(new int[] {0, 0, 0, 0});
            this.numGia.Maximum = new decimal(new int[] {2000000000, 0, 0, 0});
            this.numGia.Increment = new decimal(new int[] {100000, 0, 0, 0});
            this.numGia.ThousandsSeparator = true;
            this.numGia.Value = new decimal(new int[] {0, 0, 0, 0});
            this.numGia.Location = new System.Drawing.Point(164, 258);
            this.numGia.Size = new System.Drawing.Size(180, 23);
            this.numGia.TabIndex = 16;
            this.lblCap_txtMoTa.Text = "Mô tả:";
            this.lblCap_txtMoTa.AutoSize = true;
            this.lblCap_txtMoTa.Location = new System.Drawing.Point(14, 297);
            this.lblCap_txtMoTa.TabIndex = 17;
            this.txtMoTa.Location = new System.Drawing.Point(164, 292);
            this.txtMoTa.Size = new System.Drawing.Size(762, 23);
            this.txtMoTa.TabIndex = 18;
            this.btnThemTour.Text = "Thêm tour";
            this.btnThemTour.UseVisualStyleBackColor = true;
            this.btnThemTour.Location = new System.Drawing.Point(10, 332);
            this.btnThemTour.Size = new System.Drawing.Size(120, 36);
            this.btnThemTour.TabIndex = 19;
            this.dgvDiemDung.AllowUserToAddRows = false;
            this.dgvDiemDung.AllowUserToDeleteRows = false;
            this.dgvDiemDung.ReadOnly = true;
            this.dgvDiemDung.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDiemDung.MultiSelect = false;
            this.dgvDiemDung.RowHeadersVisible = false;
            this.dgvDiemDung.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDiemDung.BackgroundColor = System.Drawing.Color.White;
            this.dgvDiemDung.Location = new System.Drawing.Point(10, 8);
            this.dgvDiemDung.Size = new System.Drawing.Size(920, 170);
            this.dgvDiemDung.TabIndex = 20;
            this.dgvDiemDung.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_numThuTu.Text = "Thứ tự:";
            this.lblCap_numThuTu.AutoSize = true;
            this.lblCap_numThuTu.Location = new System.Drawing.Point(14, 195);
            this.lblCap_numThuTu.TabIndex = 21;
            this.numThuTu.Minimum = new decimal(new int[] {1, 0, 0, 0});
            this.numThuTu.Maximum = new decimal(new int[] {50, 0, 0, 0});
            this.numThuTu.Value = new decimal(new int[] {1, 0, 0, 0});
            this.numThuTu.Location = new System.Drawing.Point(164, 190);
            this.numThuTu.Size = new System.Drawing.Size(180, 23);
            this.numThuTu.TabIndex = 22;
            this.lblCap_txtDiemDung.Text = "Tên điểm dừng:";
            this.lblCap_txtDiemDung.AutoSize = true;
            this.lblCap_txtDiemDung.Location = new System.Drawing.Point(470, 195);
            this.lblCap_txtDiemDung.TabIndex = 23;
            this.txtDiemDung.Location = new System.Drawing.Point(620, 190);
            this.txtDiemDung.Size = new System.Drawing.Size(282, 23);
            this.txtDiemDung.TabIndex = 24;
            this.chkDoiPT.Text = "Đổi phương tiện";
            this.chkDoiPT.AutoSize = true;
            this.chkDoiPT.UseVisualStyleBackColor = true;
            this.chkDoiPT.Location = new System.Drawing.Point(164, 228);
            this.chkDoiPT.TabIndex = 25;
            this.chkAn.Text = "Có nơi ăn";
            this.chkAn.AutoSize = true;
            this.chkAn.UseVisualStyleBackColor = true;
            this.chkAn.Location = new System.Drawing.Point(620, 228);
            this.chkAn.TabIndex = 26;
            this.chkKS.Text = "Có khách sạn";
            this.chkKS.AutoSize = true;
            this.chkKS.UseVisualStyleBackColor = true;
            this.chkKS.Location = new System.Drawing.Point(164, 262);
            this.chkKS.TabIndex = 27;
            this.lblCap_numSao.Text = "Hạng sao:";
            this.lblCap_numSao.AutoSize = true;
            this.lblCap_numSao.Location = new System.Drawing.Point(470, 263);
            this.lblCap_numSao.TabIndex = 28;
            this.numSao.Minimum = new decimal(new int[] {2, 0, 0, 0});
            this.numSao.Maximum = new decimal(new int[] {5, 0, 0, 0});
            this.numSao.Value = new decimal(new int[] {3, 0, 0, 0});
            this.numSao.Enabled = false;
            this.numSao.Location = new System.Drawing.Point(620, 258);
            this.numSao.Size = new System.Drawing.Size(180, 23);
            this.numSao.TabIndex = 29;
            this.lblCap_txtGhiChuDD.Text = "Ghi chú:";
            this.lblCap_txtGhiChuDD.AutoSize = true;
            this.lblCap_txtGhiChuDD.Location = new System.Drawing.Point(14, 297);
            this.lblCap_txtGhiChuDD.TabIndex = 30;
            this.txtGhiChuDD.Location = new System.Drawing.Point(164, 292);
            this.txtGhiChuDD.Size = new System.Drawing.Size(762, 23);
            this.txtGhiChuDD.TabIndex = 31;
            this.btnThemDD.Text = "Thêm điểm dừng";
            this.btnThemDD.UseVisualStyleBackColor = true;
            this.btnThemDD.Location = new System.Drawing.Point(10, 332);
            this.btnThemDD.Size = new System.Drawing.Size(158, 36);
            this.btnThemDD.TabIndex = 32;
            this.dgvChang.AllowUserToAddRows = false;
            this.dgvChang.AllowUserToDeleteRows = false;
            this.dgvChang.ReadOnly = true;
            this.dgvChang.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvChang.MultiSelect = false;
            this.dgvChang.RowHeadersVisible = false;
            this.dgvChang.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvChang.BackgroundColor = System.Drawing.Color.White;
            this.dgvChang.Location = new System.Drawing.Point(10, 8);
            this.dgvChang.Size = new System.Drawing.Size(920, 170);
            this.dgvChang.TabIndex = 33;
            this.dgvChang.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_numChang.Text = "Chặng thứ:";
            this.lblCap_numChang.AutoSize = true;
            this.lblCap_numChang.Location = new System.Drawing.Point(14, 195);
            this.lblCap_numChang.TabIndex = 34;
            this.numChang.Minimum = new decimal(new int[] {1, 0, 0, 0});
            this.numChang.Maximum = new decimal(new int[] {50, 0, 0, 0});
            this.numChang.Value = new decimal(new int[] {1, 0, 0, 0});
            this.numChang.Location = new System.Drawing.Point(164, 190);
            this.numChang.Size = new System.Drawing.Size(180, 23);
            this.numChang.TabIndex = 35;
            this.lblCap_cboPT.Text = "Phương tiện:";
            this.lblCap_cboPT.AutoSize = true;
            this.lblCap_cboPT.Location = new System.Drawing.Point(470, 195);
            this.lblCap_cboPT.TabIndex = 36;
            this.cboPT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPT.FormattingEnabled = true;
            this.cboPT.Location = new System.Drawing.Point(620, 190);
            this.cboPT.Size = new System.Drawing.Size(282, 23);
            this.cboPT.TabIndex = 37;
            this.lblCap_txtGhiChuPT.Text = "Ghi chú:";
            this.lblCap_txtGhiChuPT.AutoSize = true;
            this.lblCap_txtGhiChuPT.Location = new System.Drawing.Point(14, 229);
            this.lblCap_txtGhiChuPT.TabIndex = 38;
            this.txtGhiChuPT.Location = new System.Drawing.Point(164, 224);
            this.txtGhiChuPT.Size = new System.Drawing.Size(762, 23);
            this.txtGhiChuPT.TabIndex = 39;
            this.btnThemChang.Text = "Gắn phương tiện";
            this.btnThemChang.UseVisualStyleBackColor = true;
            this.btnThemChang.Location = new System.Drawing.Point(10, 264);
            this.btnThemChang.Size = new System.Drawing.Size(167, 36);
            this.btnThemChang.TabIndex = 40;
            this.dgvTQ.AllowUserToAddRows = false;
            this.dgvTQ.AllowUserToDeleteRows = false;
            this.dgvTQ.ReadOnly = true;
            this.dgvTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvTQ.MultiSelect = false;
            this.dgvTQ.RowHeadersVisible = false;
            this.dgvTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTQ.BackgroundColor = System.Drawing.Color.White;
            this.dgvTQ.Location = new System.Drawing.Point(10, 8);
            this.dgvTQ.Size = new System.Drawing.Size(920, 170);
            this.dgvTQ.TabIndex = 41;
            this.dgvTQ.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.lblCap_cboDTQ.Text = "Điểm tham quan:";
            this.lblCap_cboDTQ.AutoSize = true;
            this.lblCap_cboDTQ.Location = new System.Drawing.Point(14, 195);
            this.lblCap_cboDTQ.TabIndex = 42;
            this.cboDTQ.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDTQ.FormattingEnabled = true;
            this.cboDTQ.Location = new System.Drawing.Point(164, 190);
            this.cboDTQ.Size = new System.Drawing.Size(282, 23);
            this.cboDTQ.TabIndex = 43;
            this.lblCap_numThuTuTQ.Text = "Thứ tự:";
            this.lblCap_numThuTuTQ.AutoSize = true;
            this.lblCap_numThuTuTQ.Location = new System.Drawing.Point(470, 195);
            this.lblCap_numThuTuTQ.TabIndex = 44;
            this.numThuTuTQ.Minimum = new decimal(new int[] {1, 0, 0, 0});
            this.numThuTuTQ.Maximum = new decimal(new int[] {50, 0, 0, 0});
            this.numThuTuTQ.Value = new decimal(new int[] {1, 0, 0, 0});
            this.numThuTuTQ.Location = new System.Drawing.Point(620, 190);
            this.numThuTuTQ.Size = new System.Drawing.Size(180, 23);
            this.numThuTuTQ.TabIndex = 45;
            this.btnThemTQ.Text = "Gắn điểm TQ";
            this.btnThemTQ.UseVisualStyleBackColor = true;
            this.btnThemTQ.Location = new System.Drawing.Point(10, 230);
            this.btnThemTQ.Size = new System.Drawing.Size(131, 36);
            this.btnThemTQ.TabIndex = 46;
            this.tp1.Text = "Tour";
            this.tp1.UseVisualStyleBackColor = true;
            this.tp1.Location = new System.Drawing.Point(4, 26);
            this.tp1.Size = new System.Drawing.Size(940, 386);
            this.tp1.TabIndex = 47;
            this.tp2.Text = "Điểm dừng";
            this.tp2.UseVisualStyleBackColor = true;
            this.tp2.Location = new System.Drawing.Point(4, 26);
            this.tp2.Size = new System.Drawing.Size(940, 386);
            this.tp2.TabIndex = 48;
            this.tp3.Text = "Phương tiện theo chặng";
            this.tp3.UseVisualStyleBackColor = true;
            this.tp3.Location = new System.Drawing.Point(4, 26);
            this.tp3.Size = new System.Drawing.Size(940, 386);
            this.tp3.TabIndex = 49;
            this.tp4.Text = "Điểm tham quan";
            this.tp4.UseVisualStyleBackColor = true;
            this.tp4.Location = new System.Drawing.Point(4, 26);
            this.tp4.Size = new System.Drawing.Size(940, 386);
            this.tp4.TabIndex = 50;
            this.tabTour.Location = new System.Drawing.Point(16, 136);
            this.tabTour.Size = new System.Drawing.Size(948, 418);
            this.tabTour.TabIndex = 51;
            this.tabTour.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.pnlHeader.Controls.Add(this.lblTitle);
            this.pnlHeader.Controls.Add(this.btnDong);
            this.Controls.Add(this.pnlHeader);
            this.pnlCard1.Controls.Add(this.lblCap_cboTour);
            this.pnlCard1.Controls.Add(this.cboTour);
            this.Controls.Add(this.pnlCard1);
            this.tp1.Controls.Add(this.dgvTour);
            this.tp1.Controls.Add(this.lblCap_txtMa);
            this.tp1.Controls.Add(this.txtMa);
            this.tp1.Controls.Add(this.lblCap_txtTen);
            this.tp1.Controls.Add(this.txtTen);
            this.tp1.Controls.Add(this.lblCap_numNgay);
            this.tp1.Controls.Add(this.numNgay);
            this.tp1.Controls.Add(this.lblCap_numDem);
            this.tp1.Controls.Add(this.numDem);
            this.tp1.Controls.Add(this.lblCap_numGia);
            this.tp1.Controls.Add(this.numGia);
            this.tp1.Controls.Add(this.lblCap_txtMoTa);
            this.tp1.Controls.Add(this.txtMoTa);
            this.tp1.Controls.Add(this.btnThemTour);
            this.tp2.Controls.Add(this.dgvDiemDung);
            this.tp2.Controls.Add(this.lblCap_numThuTu);
            this.tp2.Controls.Add(this.numThuTu);
            this.tp2.Controls.Add(this.lblCap_txtDiemDung);
            this.tp2.Controls.Add(this.txtDiemDung);
            this.tp2.Controls.Add(this.chkDoiPT);
            this.tp2.Controls.Add(this.chkAn);
            this.tp2.Controls.Add(this.chkKS);
            this.tp2.Controls.Add(this.lblCap_numSao);
            this.tp2.Controls.Add(this.numSao);
            this.tp2.Controls.Add(this.lblCap_txtGhiChuDD);
            this.tp2.Controls.Add(this.txtGhiChuDD);
            this.tp2.Controls.Add(this.btnThemDD);
            this.tp3.Controls.Add(this.dgvChang);
            this.tp3.Controls.Add(this.lblCap_numChang);
            this.tp3.Controls.Add(this.numChang);
            this.tp3.Controls.Add(this.lblCap_cboPT);
            this.tp3.Controls.Add(this.cboPT);
            this.tp3.Controls.Add(this.lblCap_txtGhiChuPT);
            this.tp3.Controls.Add(this.txtGhiChuPT);
            this.tp3.Controls.Add(this.btnThemChang);
            this.tp4.Controls.Add(this.dgvTQ);
            this.tp4.Controls.Add(this.lblCap_cboDTQ);
            this.tp4.Controls.Add(this.cboDTQ);
            this.tp4.Controls.Add(this.lblCap_numThuTuTQ);
            this.tp4.Controls.Add(this.numThuTuTQ);
            this.tp4.Controls.Add(this.btnThemTQ);
            this.tabTour.Controls.Add(this.tp1);
            this.tabTour.Controls.Add(this.tp2);
            this.tabTour.Controls.Add(this.tp3);
            this.tabTour.Controls.Add(this.tp4);
            this.Controls.Add(this.tabTour);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(980, 570);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "FrmTour";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Tour - hành trình";
            this.AutoScroll = true;
            this.cboTour.SelectedIndexChanged += new System.EventHandler(this.cboTour_SelectedIndexChanged);
            this.btnThemTour.Click += new System.EventHandler(this.btnThemTour_Click);
            this.chkKS.CheckedChanged += new System.EventHandler(this.chkKS_CheckedChanged);
            this.btnThemDD.Click += new System.EventHandler(this.btnThemDD_Click);
            this.btnThemChang.Click += new System.EventHandler(this.btnThemChang_Click);
            this.btnThemTQ.Click += new System.EventHandler(this.btnThemTQ_Click);
            this.btnThemTour.Click += new System.EventHandler(this.btnThemTour_Click);
            this.chkKS.CheckedChanged += new System.EventHandler(this.chkKS_CheckedChanged);
            this.btnThemDD.Click += new System.EventHandler(this.btnThemDD_Click);
            this.btnThemChang.Click += new System.EventHandler(this.btnThemChang_Click);
            this.btnThemTQ.Click += new System.EventHandler(this.btnThemTQ_Click);
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            this.Load += new System.EventHandler(this.FrmTour_Load);
            this.pnlHeader.ResumeLayout(false);
            this.pnlCard1.ResumeLayout(false);
            this.tabTour.ResumeLayout(false);
            this.tp1.ResumeLayout(false);
            this.tp2.ResumeLayout(false);
            this.tp3.ResumeLayout(false);
            this.tp4.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.Panel pnlCard1;
        private System.Windows.Forms.Label lblCap_cboTour;
        private System.Windows.Forms.ComboBox cboTour;
        private System.Windows.Forms.TabControl tabTour;
        private System.Windows.Forms.TabPage tp1;
        private System.Windows.Forms.TabPage tp2;
        private System.Windows.Forms.TabPage tp3;
        private System.Windows.Forms.TabPage tp4;
        private System.Windows.Forms.DataGridView dgvTour;
        private System.Windows.Forms.Label lblCap_txtMa;
        private System.Windows.Forms.TextBox txtMa;
        private System.Windows.Forms.Label lblCap_txtTen;
        private System.Windows.Forms.TextBox txtTen;
        private System.Windows.Forms.Label lblCap_numNgay;
        private System.Windows.Forms.NumericUpDown numNgay;
        private System.Windows.Forms.Label lblCap_numDem;
        private System.Windows.Forms.NumericUpDown numDem;
        private System.Windows.Forms.Label lblCap_numGia;
        private System.Windows.Forms.NumericUpDown numGia;
        private System.Windows.Forms.Label lblCap_txtMoTa;
        private System.Windows.Forms.TextBox txtMoTa;
        private System.Windows.Forms.Button btnThemTour;
        private System.Windows.Forms.DataGridView dgvDiemDung;
        private System.Windows.Forms.Label lblCap_numThuTu;
        private System.Windows.Forms.NumericUpDown numThuTu;
        private System.Windows.Forms.Label lblCap_txtDiemDung;
        private System.Windows.Forms.TextBox txtDiemDung;
        private System.Windows.Forms.CheckBox chkDoiPT;
        private System.Windows.Forms.CheckBox chkAn;
        private System.Windows.Forms.CheckBox chkKS;
        private System.Windows.Forms.Label lblCap_numSao;
        private System.Windows.Forms.NumericUpDown numSao;
        private System.Windows.Forms.Label lblCap_txtGhiChuDD;
        private System.Windows.Forms.TextBox txtGhiChuDD;
        private System.Windows.Forms.Button btnThemDD;
        private System.Windows.Forms.DataGridView dgvChang;
        private System.Windows.Forms.Label lblCap_numChang;
        private System.Windows.Forms.NumericUpDown numChang;
        private System.Windows.Forms.Label lblCap_cboPT;
        private System.Windows.Forms.ComboBox cboPT;
        private System.Windows.Forms.Label lblCap_txtGhiChuPT;
        private System.Windows.Forms.TextBox txtGhiChuPT;
        private System.Windows.Forms.Button btnThemChang;
        private System.Windows.Forms.DataGridView dgvTQ;
        private System.Windows.Forms.Label lblCap_cboDTQ;
        private System.Windows.Forms.ComboBox cboDTQ;
        private System.Windows.Forms.Label lblCap_numThuTuTQ;
        private System.Windows.Forms.NumericUpDown numThuTuTQ;
        private System.Windows.Forms.Button btnThemTQ;
    }
}
